### ISSUE TITLE
[Request] Option to not teleport when clicking on the log

### ISSUE THREAD

**Issue by SuicidalBomb** [MidoriKami/ZodiacBuddy#25]
Looking around at multiple options is a pain when it attempts to teleport constantly

**Comment by Mitsarugi** [comment]
Agreed , it would be nice to be able to select if we want the teleport or not.
And/Or a confirmation window maybe? ^^

**Comment by Mitsarugi** [comment]
The "Disable Teleport" checkbox doesnt seem to change anything, it still teleports you.

**Comment by Mitsarugi** [comment]
Works like a charm! Thank you for adding this function ^^
