### ISSUE TITLE
[Bug] Dungeon incorrectly shown as bonus

### ISSUE THREAD

**Issue by choreutes** [MidoriKami/ZodiacBuddy#29]
I'm experiencing the opposite issue to #26. I just ran Brayflox's Longstop (Hard) as it was shown to give bonus light, but got bright light afterwards which is the non-bonus light iirc.

Time of occurence: 2023-03-27 22:29 CEST / 20:20 ST

![grafik](https://user-images.githubusercontent.com/1265189/228061632-251839f1-f309-487f-b29c-cdc7e27e636d.png)

**Comment by Hiroa** [comment]
Yeah 32 is not a light bonus for Brayflox (Hard).
I have some ideas of how it could happen. I need to try them tomorrow.

**Comment by DoubleMCA** [comment]
This is still happening.

https://imgur.com/a/4bmi41Q

**Comment by DoubleMCA** [comment]
Would it be possible for the addon to detect that the bonus is not in effect any longer and remove the bonus light message?

**Comment by Hiroa** [comment]
It's possible, but I would keep that as a last option. I'm confident that should not be needed.  
Will trying to fix flaws from player reconnecting during duty or joining an ongoing duty, I have made the detection worst for the normal cases that has lead to the case of today.

**Comment by MidoriKami** [comment]
Is this still an issue?
