### ISSUE TITLE
Doesn't detect bonus light for Snowcloak

### ISSUE THREAD

**Issue by Lordvbcool** [MidoriKami/ZodiacBuddy#35]
I did Snowcloak multiple time this morning and each time it was giving me Blinding (96) light which, according to the wiki, is what it gives when it's in bonus
The Zodiac Body plugin indicated correctly in my echo chat that I gained 96 light but never detected that this was the bonus light amount so it wasn't shared with everybody else

**Comment by Hiroa** [comment]
Territory Id seems to have changed from 371 to 1062.
I'll check the other id later today.
