### ISSUE TITLE
Teleport not working 7.1

### ISSUE THREAD

**Issue by dennischen0** [MidoriKami/ZodiacBuddy#39]
Teleports dont seem to be working for me for the 7.1 update.

**Comment by farbod21** [comment]
Yes, doesn't work for me either.

**Comment by MidoriKami** [comment]
Does interacting with the book trigger other things such as opening duty finder?

**Comment by snow13579** [comment]
yup the auto port and pin dont work for the books ether.

**Comment by rebelsong42** [comment]
Doesn't work for me either. I'm in the books, so I can confirm the teleport not working, as well as opening duty finder or printing the objective in the chat log.
